name: Auto Build KernelSU For MI8SE(sirius)

on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  AutoKSUForSirius:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full
          sudo apt clean
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date +%F)" >> $GITHUB_ENV
      - name: Cloning Sources and Toolchain
        run: |
          git clone https://github.com/liqidecg/android_kernel_xiaomi_sdm710 --depth=1 -b lineage-20 --recurse-submodules android_kernel_xiaomi_sdm710_LineageOS
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r445002 --depth=1 --single-branch --no-tags -b 12.0 ~/clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r47 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
          git clone https://github.com/SakuraNotStupid/AnyKernel3
      - name: Applying Kernel Patch(LineageOS)
        run: |
           cd android_kernel_xiaomi_sdm710_LineageOS/KernelSU
           wget https://github.com/tiann/KernelSU/commit/128f0aa87371ddc05331cf9e13c74bba6887449e.patch
           patch -p1 < 128f0aa87371ddc05331cf9e13c74bba6887449e.patch
           rm -rf *.patch
      - name: Compiling Kernel(LineageOS)
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd android_kernel_xiaomi_sdm710_LineageOS
          make O="$output_dir" \
                      sdm670-perf_defconfig \
                      xiaomi/sdm710-common.config \
                      xiaomi/sirius.config
          make -j $(nproc) \
                       O="$output_dir" \
                       CC=clang
          popd
      - name: Packaging the Kernel(LineageOS)
        run: |
          cp -v android_kernel_xiaomi_sdm710_LineageOS/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../MI8SE_KernelSU_CI-${{ env.BUILD_TIME }}_LineageOS.zip *
          popd
      - name: Creating Config Info
        run: |
          echo "Device: MI 8 SE
          Code: Sirius/Xmsirius
          Build Time: ${{ env.BUILD_TIME }}
          CI Auto Build Without Any Test!!
          KernelSU For MI8SE" >> INFO.txt
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: MI8SE_KernelSU_CI-${{ env.BUILD_TIME }}_LineageOS.zip
          name: "MI8SE_KernelSU_CI-${{ env.BUILD_TIME }}"
          tag: " ${{ env.BUILD_TIME }}_MI8SE_KernelSU_CI"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
